### ISSUE TITLE
process has died  exit code -11

### ISSUE THREAD

**Issue by Inventoryo** [ethz-asl/segmap#120]
**I have compiled the file successfully .When I ran the demo with kitti_localization.launch and others too, I got the following error.**
[ INFO] [1545718185.967992005]: rviz version 1.12.16
[ INFO] [1545718185.968034595]: compiled against Qt version 5.5.1
[ INFO] [1545718185.968044919]: compiled against OGRE version 1.9.0 (Ghadamon)
[player-3] process has finished cleanly
log file: /home/bb/.ros/log/ad0d31a2-080b-11e9-b272-107b447b4ab6/player-3*.log
[ INFO] [1545718186.433949523]: Stereo is NOT SUPPORTED
[ INFO] [1545718186.434028895]: OpenGl version: 4.5 (GLSL 4.5).
[segmapper-4] process has died [pid 5589, exit code -11, cmd /home/bb/segmap_ws/devel/lib/segmapper/segmapper_node __name:=segmapper __log:=/home/bb/.ros/log/ad0d31a2-080b-11e9-b272-107b447b4ab6/segmapper-4.log].
log file: /home/bb/.ros/log/ad0d31a2-080b-11e9-b272-107b447b4ab6/segmapper-4*.log
[visualizer-2] process has finished cleanly

**It seems like the segmapper_node won't start.
When I checked the log file I got this:**

[rosmaster.threadpool][ERROR] 2018-12-25 14:09:46,182: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused.

**Can anyone help me fix it?**

**Comment by hel4859** [comment]
do you solve the problem？i face the same problem.

**Comment by ZWu-UM** [comment]
I got the same error. Wondering if this is an issue for everyone or just because I did something stupid.  My system is Ubuntu16, GTX1080, cuda10. The only difference I noticed is that I ran the roslaunch command inside the segmappyenv.

**Comment by LiShuaixin** [comment]
@hel4859  Hi, have you solved the problem? I met the same issue, could you please give me some suggestion?

**Comment by hel4859** [comment]
i gave up. But if you find the method to solve the problem, please tell me.
